version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && foreman start -f Procfile.dev"
    volumes:
      - .:/tracker
    ports:
      - "3000:3000"
    depends_on:
      - db